x-boilerplate-go-lib-private-postgres-common:
  &boilerplate-go-lib-private-postgres-common
  image: postgres:latest
  restart: always
  user: ${USER_EXECUTE_COMMAND}
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -p ${DB_PORT}" ]
    interval: 10s
    timeout: 5s
    retries: 5
  networks:
    - boilerplate-go-lib-private-network

services:
  boilerplate-go-lib-private:
    container_name: boilerplate-go-lib-private
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${PROTO_PORT}:${PROTO_PORT}
    volumes:
      - .:/usr/src/app
    depends_on:
      - boilerplate-go-lib-private-postgres-primary
      - boilerplate-go-lib-private-postgres-replica
    networks:
      - boilerplate-go-lib-private-network

  boilerplate-go-lib-private-valkey:
    image: valkey/valkey:latest
    container_name: boilerplate-go-lib-private-valkey
    restart: always
    env_file:
      - .env
    environment:
      - VALKEY_USER=${VALKEY_USER}
      - VALKEY_PASSWORD=${VALKEY_PASSWORD}
    command: [ "redis-server", "--requirepass", "${VALKEY_PASSWORD}", "--user", "${VALKEY_USER}",  "--port ${VALKEY_PORT}" ]
    ports:
      - ${VALKEY_PORT}:${VALKEY_PORT}
    volumes:
      - valkey-data:/data
    networks:
      - boilerplate-go-lib-private-network

  boilerplate-go-lib-private-postgres-primary:
    <<: *boilerplate-go-lib-private-postgres-common
    container_name: boilerplate-go-lib-private-postgres-primary
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      PGPORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    command: |
      postgres
      -c wal_level=replica
      -c hot_standby=on
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby_feedback=on
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  boilerplate-go-lib-private-postgres-replica:
    <<: *boilerplate-go-lib-private-postgres-common
    container_name: boilerplate-go-lib-private-postgres-replica
    ports:
      - ${DB_REPLICA_PORT}:${DB_REPLICA_PORT}
    environment:
      PGPORT: ${DB_REPLICA_PORT}
      PGUSER: ${REPLICATION_USER}
      PGPASSWORD: ${REPLICATION_PASSWORD}
    command: |
      bash -c "
      if [ ! -d \"/var/lib/postgresql/data\" ] || [ ! -f \"/var/lib/postgresql/data/postgresql.conf\" ]; then
        until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot --host=boilerplate-go-lib-private-postgres-primary --port=${DB_PORT}
        do
          echo 'Waiting for boilerplate-go-lib-private-postgres-primary to connect...'
          sleep 1s
        done
        echo 'Backup done..., starting boilerplate-go-lib-private-postgres-replica...'
        chmod 0700 /var/lib/postgresql/data
        # Ensure the port is set to use for the replica
        sed -i 's/^#port.*/port = ${DB_REPLICA_PORT}/' /var/lib/postgresql/data/postgresql.conf
      fi
      exec postgres -c config_file=/var/lib/postgresql/data/postgresql.conf
      "
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_REPLICA_USER} -p ${DB_REPLICA_PORT}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      boilerplate-go-lib-private-postgres-primary:
        condition: service_healthy

volumes:
  postgres-data:
  valkey-data:

networks:
  boilerplate-go-lib-private-network:
    driver: bridge